### ISSUE TITLE
Plot multiple network interfaces

### ISSUE THREAD

**Issue by ptrktn** [juliojsb/sarviewer#10]
One suggestion for future development.

In the properties file, one could specify more than one network interface.

network_interface="eth0 ib0 bond1"

Then, in system_data_reader.sh, just loop over the values.

for i in $network_interface ; do
       sar -n DEV -f $sysstat_logdir/$sa_file -s $start_time -e $end_time | grep -w $i | grep -v "Average" > data/netinterface_$i.dat
done

Then, in the plotter.sh do similar task. You can pass parameters to gnuplot by using the -e option, e.g. gnuplot -e "net='$i'" netinterface.gplot

**Comment by juliojsb** [comment]
Interesting idea, I will have it in mind for the next releases. 

I also have to make some adjustments to the Python scripts so they have the same functionality as the gnuplot ones, so once I have everything working I will upload it.
