### ISSUE TITLE
Autodetect the first network interface name that is up

### ISSUE THREAD

**Issue by sebma** [juliojsb/sarviewer#13]
Hi,

Why not autodetect the first network interface name that is up ?

Like this  : 
```config
network_interface=$(ip -o link show up | gawk -F '\\s|:' '!/\<lo\>/{print$3;exit}')
```

**Comment by juliojsb** [comment]
Hi,

We could detect the devices that are up and connected to the network:

```
ip -o link show up | grep LOWER_UP | gawk -F '\\s|:' '!/\<lo\>/{print$3;exit}'
```
But right now, I won't be introducing changes or updates to the tool, as it is unmaintained.

Regards,
