### ISSUE TITLE
running error~

### ISSUE THREAD

**Issue by gongyue666** [juliojsb/sarviewer#6]
./data_collector.sh 
Please specify the number of samples to take-> 2
Please specify the sample interval (take sample every X seconds)-> 1
Taking 2 samples with 1 seconds interval
Total time to collect all data: 2 seconds
----------------------------------
>>> Collecting data
>>> Please wait until data collection is completed
----------------------------------
- You can abort this script with Ctrl+C, but have in mind the data will stop being collected when you cancel it.
- You will also need to manually launch script plotter.sh to generate the graphs.
----------------------------------
>>> Just 5 seconds more while processing all data
----------------------------------
Done!
"netinterface.gplot", line 41: warning: Skipping data file with no valid points
"netinterface.gplot", line 41: warning: Skipping data file with no valid points

plot '../../data/netinterface.dat' using 1:5 title 'Kilobytes received per second' with l ls 1,      ''                            using 1:6 title 'Kilobytes sent per second' with l ls 2
                                                                                                                                                                                          ^
"netinterface.gplot", line 41: x range is invalid
my options:
gnuplot 5.0 patchlevel 3
Python 2.7.12
ubuntu 16.04

**Comment by juliojsb** [comment]
Hi,

It seems only netinterface plot is failing. What's your network interface name? By default sarviewer uses **eth0** as specified in **sarviewer.properties**

Regards,
Jota
