### ISSUE TITLE
Wrong used values in ram graph

### ISSUE THREAD

**Issue by onkelringnes** [juliojsb/sarviewer#8]
I get wrong values for Used, Buffers and Cached. The fix in issue #1 had to be reverted on my part. That issue shows two different outputs from sar -r: one with an annoying AM/PM column and one without. Obviously the column numbers will be shifted depending on the extra AM/PM column.

Not sure if there are ways to tell sysstat to stick to 24h timestamps in the output, or if sarviewer can be adapted to convert AM/PM to 24h when making the ram.dat file? Anyway, these changes in ram.gplot fixed it for me:

From:
     ''                   using 1:($5/1024) title 'Buffers' with l ls 2, \
     ''                   using 1:($6/1024) title 'Cached' with l ls 3, \
     ''                   using 1:($3/1024-$5/1024-$6/1024) title 'Used' with l ls 4
To:
     ''                   using 1:($6/1024) title 'Buffers' with l ls 2, \
     ''                   using 1:($7/1024) title 'Cached' with l ls 3, \
     ''                   using 1:($4/1024-$6/1024-$7/1024) title 'Used' with l ls 4_

**Comment by onkelringnes** [comment]
Possibly add this before directing to the dat file in system_data_reader.sh?
`| sed "s/ AM //g;s/ PM //g"`

**Comment by juliojsb** [comment]
Hello Johnny,

The hour format is set in the **LC_TIME** variable in **sarviewer.properties** file. It should default to 24h

```
# LC_TIME controls time format. To correctly draw the graphs, we need 24 hour time format
# By default, POSIX. DO NOT CHANGE
export LC_TIME="POSIX"
```
I have never seen that behavior in sarviewer, all .dat files should be in 24h format as specified by that variable.

Regards,

**Comment by onkelringnes** [comment]
This was a standard sysstat installation on Ubuntu 16.04. I've verified that the LC_TIME variable is not set in any of the config files on other 16.04/18.04 hosts either.

Here are the variables in the sysstat configuration file.
```
# grep -v ^# /etc/sysstat/sysstat | grep -v ^$
HISTORY=7
COMPRESSAFTER=10
SADC_OPTIONS="-S DISK"
SA_DIR=/var/log/sysstat
ZIP="xz"
```

I could of course add LC_TIME, but I've got many servers so it would be preferable to have it work regardless of the LC_TIME setting.

**Comment by juliojsb** [comment]
I am just talking about the scripts in this repository -not system wide configuration- and the data they generate, which is 24h format by default.
