### ISSUE TITLE
Consider explicit time axis formatting in gnuplot

### ISSUE THREAD

**Issue by ptrktn** [juliojsb/sarviewer#9]
Great tool, thanks for making it available.

I found out one cosmetic issue when running the scripts in SL6. The x axis was showing time and date, date set to 1/1. It is therefore better to specify the X axis format explicitly as follows.

diff --git a/plotters/gnuplot/contextsw.gplot b/plotters/gnuplot/contextsw.gplot
index a9d048f..ef0cfbc 100644
--- a/plotters/gnuplot/contextsw.gplot
+++ b/plotters/gnuplot/contextsw.gplot
@@ -29,6 +29,7 @@ set tics nomirror
 set autoscale xy
 set xdata time
 set timefmt "%H:%M:%S"
+set format x "%H:%M"
 set xlabel "Time"
 set ylabel "Context switches"

**Comment by juliojsb** [comment]
Nice tip! The scripts are designed to get data from a specific day so it's better to format the axis following your suggestion.

Added in last commit.
